name: CI checks
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version:
          - "22.3"
          - "23.3"
          - "24.3"
          - "25.3"
          - "26"
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: rebar3 compile

    - name: Run Proper Tests
      run: rebar3 proper -c

    - name: Coverage
      run: rebar3 cover --verbose --min_coverage 85

    - name: Run Xref
      run: rebar3 xref

    - name: Generate Documentation
      run: rebar3 edoc

    - name: Run dialyzer
      run: rebar3 dialyzer
